steps:
  - command: "echo 'bootstrap'"
    label: Bootstrap
    key: bootstrap

  - command: "echo 'lint'"
    label: Lint
    key: lint

  - command: "echo 'Build OSS'"
    label: 'Build OSS'
    key: build-oss
    depends_on: bootstrap

  - command: "echo 'Build Default'"
    label: 'Build Default'
    key: build-default
    depends_on: bootstrap

  - command: "echo 'Jest'"
    label: Jest
    key: jest
    depends_on: bootstrap
    parallelism: 15

  - command: "echo 'Post-Jest'"
    label: 'Post-Jest'
    key: post-jest
    depends_on: jest

  - command: "echo 'OSS CI Group'"
    label: OSS CI Group
    depends_on: build-oss
    parallelism: 10

  - command: "echo 'OSS Firefox'"
    label: OSS Firefox
    depends_on: build-oss

  - command: "echo 'Default CI Group'"
    label: Default CI Group
    depends_on: build-default
    parallelism: 15

  - wait: ~
    continue_on_failure: true

  - command: "echo 'Post-All'"
    label: Post All
