env:
  IGNORE_SHIP_CI_STATS_ERROR: 'true'
steps:
  - command: .buildkite/setup/pre_build.sh
    label: Pre-Build
  - wait
  - command: .buildkite/scripts/jobs/build.sh
    label: Build Kibana Distribution
    agents:
      queue: bootstrap
    key: build

  - command: .buildkite/scripts/jobs/build_oss.sh
    label: Build OSS Kibana Distribution
    agents:
      queue: bootstrap
    key: build-oss

  - command: .buildkite/scripts/xpack-cigroup.sh
    label: 'Default CI Group %n'
    parallelism: 31
    agents:
      queue: ci-group-6
    artifact_paths: target/junit/**/*.xml
    depends_on: build

  - command: .buildkite/scripts/oss-cigroup.sh
    label: 'OSS CI Group %n'
    parallelism: 12
    agents:
      queue: ci-group-4d
    artifact_paths: target/junit/**/*.xml
    depends_on: build-oss

  - command: .buildkite/scripts/test/jest_integration.sh
    label: 'Jest Integration Tests'
    agents:
      queue: jest
    artifact_paths: target/junit/**/*.xml

  - command: .buildkite/scripts/test/api_integration.sh
    label: 'API Integration Tests'
    agents:
      queue: jest
    artifact_paths: target/junit/**/*.xml

  - wait

  - trigger: 'kibana-elasticsearch-snapshot-promote'
    async: true
    build:
      env:
        ES_SNAPSHOT_MANIFEST: '$ES_SNAPSHOT_MANIFEST'
      branch: '$BUILDKITE_BRANCH'

  - wait: ~
    continue_on_failure: true
  - plugins:
      - junit-annotate#v1.9.0:
          artifacts: target/junit/**/*.xml
  - wait: ~
    continue_on_failure: true
  - command: .buildkite/setup/post_build.sh
    label: Post-Build
