steps:
  - command: .buildkite/scripts/es_snapshots/build.sh
    label: Build ES Snapshot
    agents:
      queue: bootstrap
  - wait
  - trigger: 'kibana-elasticsearch-snapshot-verify'
    async: true
    build:
      env:
        ES_SNAPSHOT_MANIFEST: '$ES_SNAPSHOT_MANIFEST'
      branch: '$BUILDKITE_BRANCH'
