steps:
  - command: "echo 'Pretending this is a build job'"
  - wait
  - command: 'CI_GROUP=1 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 1'
  - command: 'CI_GROUP=2 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 2'
  - command: 'CI_GROUP=3 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 3'
  - command: 'CI_GROUP=4 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 4'
  - command: 'CI_GROUP=5 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 5'
  - command: 'CI_GROUP=6 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 6'
  - command: 'CI_GROUP=7 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 7'
  - command: 'CI_GROUP=8 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 8'
  - command: 'CI_GROUP=9 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 9'
  - command: 'CI_GROUP=10 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 10'
  - command: 'CI_GROUP=11 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 11'
  - command: 'CI_GROUP=12 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 12'
  - command: 'CI_GROUP=13 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 13'
