steps:
  - command: .buildkite/setup/pre_build.sh
    label: Pre-Build
  - wait
  - command: .buildkite/scripts/jobs/build.sh
    label: Build Kibana Distribution
    agents:
      queue: bootstrap
    key: build
  - command: '.buildkite/scripts/xpack-cigroup.sh'
    label: 'Default CI Group %n (+1)'
    parallelism: 29
    agents:
      queue: ci-group
    artifact_paths: target/junit/**/*.xml
    depends_on: build
  - wait: ~
    continue_on_failure: true
  - plugins:
      - junit-annotate#v1.9.0:
          artifacts: target/junit/**/*.xml
  - wait: ~
    continue_on_failure: true
  - command: .buildkite/setup/post_build.sh
    label: Post-Build
