steps:

  - command: |
      export DOCKER_BUILDKIT=1 && \
      docker build -t gcr.io/elastic-kibana-184716/buildkite/ci/base:$BUILDKITE_COMMIT -f .ci/Dockerfile . --progress plain && \
      docker push gcr.io/elastic-kibana-184716/buildkite/ci/base:$BUILDKITE_COMMIT
    label: "Bootstrap"
    agents:
      queue: bootstrap

  - wait

  - command: |
      export DOCKER_BUILDKIT=1 && \
      docker build -t gcr.io/elastic-kibana-184716/buildkite/ci/default-build:$BUILDKITE_COMMIT -f .ci/Dockerfile-build --build-arg BASE_IMAGE=gcr.io/elastic-kibana-184716/buildkite/ci/base:$BUILDKITE_COMMIT . --progress plain && \
      docker push gcr.io/elastic-kibana-184716/buildkite/ci/default-build:$BUILDKITE_COMMIT
    label: "Build"
    agents:
      queue: bootstrap
    key: default-build

  - command: .buildkite/scripts/jest_pipeline.sh | buildkite-agent pipeline upload
    label: ":jest: Upload"
    agents:
      queue: default

  - command: 'CI_GROUP=1 .ci/buildkite/xpack-cigroup.sh'
    label: 'Default CI Group 1'
    agents:
      queue: ci-group
    artifact_paths: target/junit/**/*.xml
    plugins:
      - docker#v3.8.0:
          image: 'gcr.io/elastic-kibana-184716/buildkite/ci/default-build:$BUILDKITE_COMMIT'
          propagate-environment: true
          mount-checkout: false
    depends_on: default-build

  - wait: ~
    continue_on_failure: true

  - plugins:
      - junit-annotate#v1.9.0:
          artifacts: target/junit/**/*.xml
